VERSION: 2
MODEL:
  KEYPOINT_ON: True
  META_ARCHITECTURE: "UnifyPointsFasterRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_BOX_HEAD:
    BBOX_POINTS_NUM: 16
    SEG_POINTS_NUM: 32
    KEYPOINT_POINTS_NUM: 52
    SMOOTH_L1_BETA: 0.0
    #WEIGHT for ablation study, only 0.0 or 1.0
    DET_WEIGHTS: 1
    SEG_WEIGHTS: 1
    POSE_WEIGHTS: 1
    CLS_AGNOSTIC_BBOX_REG: True
  ROI_KEYPOINT_HEAD:
    MIN_KEYPOINTS_PER_IMAGE: 0
  ROI_HEADS:
    NAME: "UnifyRes5ROIHeads"
    OUTPUT_LAYER: "UnifyFastRCNNOutputLayers"
DATASETS:
  TRAIN: ("unify_trainval_base",)
  TEST: ('misc_test_base','unify_test_base')
SOLVER:
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  MAX_TO_KEEP: 1
  IMS_PER_BATCH: 32
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WARMUP_ITERS: 200
#  CLIP_GRADIENTS:
#    ENABLED: True
#    CLIP_TYPE: "value"
#    CLIP_VALUE: 1.0
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  MIN_SIZE_TRAIN: (480, 512,544,576,608,640, 672, 704, 736, 768, 800)

TEST:
  EVAL_PERIOD: 5000
  META_TEST: True
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  NUM_WORKERS: 0
